export { teamMemberSchema, teamSchema } from './team'
export type { SocialLink, TeamMember, Team } from './team'
export { partnersSchema } from './partners'
export type { Partner, Partners } from './partners'
export { docsSchema } from './docs'
export type { DocsLink, Docs } from './docs'
export { blogPostSchema } from './blog'
export type { BlogPost } from './blog'
export { carouselSchema } from './carousel'
export type { CarouselSlide, Carousel } from './carousel'